package net.code303.kfzkennzeichen;

import java.util.HashMap;

 // This class provides a searchable list of license plates
public class LicensePlateManager {

    // Members
    private static LicensePlateManager instance = new LicensePlateManager();
    private HashMap licensePlates = new HashMap<String, LicensePlate>();

    //Constructor
    private LicensePlateManager()
    {
        // initialize the list of license plates
        this.init();
    }

    // Implements the singleton pattern
    public static LicensePlateManager getInstance() {
        return instance;
    }

    private void init() {

            licensePlates.put("A", new LicensePlate("A", "Stadt Augsburg", "Augsburg", "Bayern"));
            licensePlates.put("AA", new LicensePlate("AA", "Ostalbkreis in Aalen", "Aalen", "Baden-Württemberg"));
            licensePlates.put("AB", new LicensePlate("AB", "Landkreis Aschaffenburg", "Aschaffenburg", "Bayern"));
            licensePlates.put("ABG", new LicensePlate("ABG", "Landkreis Altenburger Land in Altenburg", "Altenburg", "Thüringen"));
            licensePlates.put("ABI", new LicensePlate("ABI", "Landkreis Anhalt-Bitterfeld in Köthen (Anhalt)", "Anhalt-Bitterfeld", "Sachsen-Anhalt"));
            licensePlates.put("AC", new LicensePlate("AC", "Städteregion Aachen", "Aachen", "Nordrhein-Westfalen"));
            licensePlates.put("AE", new LicensePlate("AE", "Vogtlandkreis", "Auerbach/Vogtl.", "Sachsen"));
            licensePlates.put("AH", new LicensePlate("AH", "Kreis Borken", "Ahaus", "Nordrhein-Westfalen"));
            licensePlates.put("AIC", new LicensePlate("AIC", "Landkreis Aichach-Friedberg in Aichach", "Aichach", "Bayern"));
            licensePlates.put("AK", new LicensePlate("AK", "Landkreis Altenkirchen (Westerwald)", "Altenkirchen", "Rheinland-Pfalz"));
            licensePlates.put("ALF", new LicensePlate("ALF", "Landkreis Hildesheim", "Alfeld (Leine)", "Niedersachsen"));
            licensePlates.put("AM", new LicensePlate("AM", "Stadt Amberg", "Amberg", "Bayern"));
            licensePlates.put("AN", new LicensePlate("AN", "Landkreis Ansbach (XX 999)", "Ansbach", "Bayern"));
            licensePlates.put("ANA", new LicensePlate("ANA", "Erzgebirgskreis", "Annaberg-Buchholz", "Sachsen"));
            licensePlates.put("ANK", new LicensePlate("ANK", "Landkreis Vorpommern-Greifswald", "Anklam", "Mecklenburg-Vorpommern"));
            licensePlates.put("AÖ", new LicensePlate("AÖ", "Landkreis Altötting", "Altötting", "Bayern"));
            licensePlates.put("AP", new LicensePlate("AP", "Landkreis Weimarer Land in Apolda", "Apolda", "Thüringen"));
            licensePlates.put("APD", new LicensePlate("APD", "Landkreis Weimarer Land", "Apolda", "Thüringen"));
            licensePlates.put("ARN", new LicensePlate("ARN", "Ilm-Kreis", "Arnstadt", "Thüringen"));
            licensePlates.put("ART", new LicensePlate("ART", "Kyffhäuserkreis", "Artern", "Thüringen"));
            licensePlates.put("AS", new LicensePlate("AS", "Landkreis Amberg-Sulzbach in Amberg", "Amberg-Sulzbach", "Bayern"));
            licensePlates.put("ASL", new LicensePlate("ASL", "Salzlandkreis", "Aschersleben", "Sachsen-Anhalt"));
            licensePlates.put("ASZ", new LicensePlate("ASZ", "Erzgebirgskreis", "Landkreis Aue-Schwarzenberg", "Sachsen"));
            licensePlates.put("AU", new LicensePlate("AU", "Erzgebirgskreis", "Aue (Sachsen)", "Sachsen"));
            licensePlates.put("AUR", new LicensePlate("AUR", "Landkreis Aurich", "Aurich", "Niedersachsen"));
            licensePlates.put("AW", new LicensePlate("AW", "Landkreis Ahrweiler in Bad Neuenahr-Ahrweiler", "Ahrweiler", "Rheinland-Pfalz"));
            licensePlates.put("AZ", new LicensePlate("AZ", "Landkreis Alzey-Worms in Alzey", "Alzey", "Rheinland-Pfalz"));
            licensePlates.put("AZE", new LicensePlate("AZE", "Landkreis Anhalt-Bitterfeld", "Anhalt-Zerbst", "Sachsen-Anhalt"));
            licensePlates.put("B", new LicensePlate("B", "Stadt Berlin", "Berlin", "Berlin"));
            licensePlates.put("BA", new LicensePlate("BA", "Landkreis Bamberg", "Bamberg", "Bayern"));
            licensePlates.put("BAD", new LicensePlate("BAD", "Stadt Baden-Baden", "Baden-Baden", "Baden-Württemberg"));
            licensePlates.put("BAR", new LicensePlate("BAR", "Landkreis Barnim in Eberswalde", "Barnim", "Brandenburg"));
            licensePlates.put("BB", new LicensePlate("BB", "Landkreis Böblingen", "Böblingen", "Baden-Württemberg"));
            licensePlates.put("BBG", new LicensePlate("BBG", "Salzlandkreis", "Bernburg", "Sachsen-Anhalt"));
            licensePlates.put("BBL", new LicensePlate("BBL", "Brandenburg, Landesregierung, Landtag und Polizei[2]", "Brandenburgische Landesregierung", "Brandenburg"));
            licensePlates.put("BC", new LicensePlate("BC", "Landkreis Biberach", "Biberach", "Baden-Württemberg"));
            licensePlates.put("BCH", new LicensePlate("BCH", "Neckar-Odenwald-Kreis", "Buchen (Odenwald)", "Baden-Württemberg"));
            licensePlates.put("BD", new LicensePlate("BD", "Deutscher Bundestag, Bundesrat, Bundespräsidialamt, Bundesregierung, Bundesministerien, Bundesfinanzverwaltung und Bundesverfassungsgericht[2]", "Bund", "bundesweit"));
            licensePlates.put("BED", new LicensePlate("BED", "Landkreis Mittelsachsen", "Brand-Erbisdorf", "Sachsen"));
            licensePlates.put("BER", new LicensePlate("BER", "Landkreis Barnim", "Bernau bei Berlin", "Brandenburg"));
            licensePlates.put("BGL", new LicensePlate("BGL", "Landkreis Berchtesgadener Land in Bad Reichenhall", "Berchtesgadener Land", "Bayern"));
            licensePlates.put("BI", new LicensePlate("BI", "Stadt Bielefeld", "Bielefeld", "Nordrhein-Westfalen"));
            licensePlates.put("BID", new LicensePlate("BID", "Landkreis Marburg-Biedenkopf", "Biedenkopf", "Hessen"));
            licensePlates.put("BIN", new LicensePlate("BIN", "Landkreis Mainz-Bingen", "Bingen", "Rheinland-Pfalz"));
            licensePlates.put("BIR", new LicensePlate("BIR", "Landkreis Birkenfeld", "Birkenfeld", "Rheinland-Pfalz"));
            licensePlates.put("BIT", new LicensePlate("BIT", "Eifelkreis Bitburg-Prüm in Bitburg", "Bitburg", "Rheinland-Pfalz"));
            licensePlates.put("BIW", new LicensePlate("BIW", "Landkreis Bautzen", "Bischofswerda", "Sachsen"));
            licensePlates.put("BK", new LicensePlate("BK", "Landkreis Börde in Haldensleben", "Börde(kreis)", "Sachsen-Anhalt"));
            licensePlates.put("BKS", new LicensePlate("BKS", "Landkreis Bernkastel-Wittlich", "Bernkastel-Kues", "Rheinland-Pfalz"));
            licensePlates.put("BL", new LicensePlate("BL", "Zollernalbkreis in Balingen", "Balingen", "Baden-Württemberg"));
            licensePlates.put("BLB", new LicensePlate("BLB", "Kreis Siegen-Wittgenstein", "Bad Berleburg", "Nordrhein-Westfalen"));
            licensePlates.put("BLK", new LicensePlate("BLK", "Burgenlandkreis in Naumburg (Saale)", "Burgenlandkreis", "Sachsen-Anhalt"));
            licensePlates.put("BM", new LicensePlate("BM", "Rhein-Erft-Kreis in Bergheim", "Bergheim", "Nordrhein-Westfalen"));
            licensePlates.put("BN", new LicensePlate("BN", "Stadt Bonn", "Bonn", "Nordrhein-Westfalen"));
            licensePlates.put("BNA", new LicensePlate("BNA", "Landkreis Leipzig", "Borna", "Sachsen"));
            licensePlates.put("BO", new LicensePlate("BO", "Stadt Bochum", "Bochum", "Nordrhein-Westfalen"));
            licensePlates.put("BÖ", new LicensePlate("BÖ", "Landkreis Börde", "Börde", "Sachsen-Anhalt"));
            licensePlates.put("BOH", new LicensePlate("BOH", "Kreis Borken", "Bocholt", "Nordrhein-Westfalen"));
            licensePlates.put("BOR", new LicensePlate("BOR", "Kreis Borken", "Borken", "Nordrhein-Westfalen"));
            licensePlates.put("BOT", new LicensePlate("BOT", "Stadt Bottrop", "Bottrop", "Nordrhein-Westfalen"));
            licensePlates.put("BP", new LicensePlate("BP", "Bundespolizei", "Bundespolizei", "bundesweit"));
            licensePlates.put("BRA", new LicensePlate("BRA", "Landkreis Wesermarsch in Brake (Unterweser)", "Brake", "Niedersachsen"));
            licensePlates.put("BRB", new LicensePlate("BRB", "Stadt Brandenburg an der Havel", "Brandenburg", "Brandenburg"));
            licensePlates.put("BRG", new LicensePlate("BRG", "Landkreis Jerichower Land", "Burg bei Magdeburg", "Sachsen-Anhalt"));
            licensePlates.put("BRL", new LicensePlate("BRL", "Landkreis Goslar", "Braunlage", "Niedersachsen"));
            licensePlates.put("BRV", new LicensePlate("BRV", "Landkreis Rotenburg (Wümme)", "Bremervörde", "Niedersachsen"));
            licensePlates.put("BS", new LicensePlate("BS", "Stadt Braunschweig", "Braunschweig", "Niedersachsen"));
            licensePlates.put("BT", new LicensePlate("BT", "Landkreis Bayreuth", "Bayreuth", "Bayern"));
            licensePlates.put("BTF", new LicensePlate("BTF", "Landkreis Anhalt-Bitterfeld", "Bitterfeld", "Sachsen-Anhalt"));
            licensePlates.put("BÜD", new LicensePlate("BÜD", "Wetteraukreis", "Büdingen", "Hessen"));
            licensePlates.put("BÜS", new LicensePlate("BÜS", "Gemeinde Büsingen am Hochrhein - Enklave in der Schweiz", "Büsingen", "Baden-Württemberg"));
            licensePlates.put("BÜZ", new LicensePlate("BÜZ", "Landkreis Rostock", "Bützow", "Mecklenburg-Vorpommern"));
            licensePlates.put("BW", new LicensePlate("BW", "Wasser- und Schifffahrtsverwaltung des Bundes", "Bundes-Wasser- und Schifffahrtsverwaltung", "bundesweit"));
            licensePlates.put("BWL", new LicensePlate("BWL", "Baden-Württemberg, Landesregierung, Landtag und Polizei[2]", "Baden-Württembergischer Landtag", "Baden-Württemberg"));
            licensePlates.put("BYL", new LicensePlate("BYL", "Bayern, Landesregierung und Landtag", "Bayerischer Landtag", "Bayern"));
            licensePlates.put("BZ", new LicensePlate("BZ", "Landkreis Bautzen", "Bautzen", "Sachsen"));
            licensePlates.put("C", new LicensePlate("C", "Stadt Chemnitz", "Chemnitz", "Sachsen"));
            licensePlates.put("CA", new LicensePlate("CA", "Landkreis Oberspreewald-Lausitz", "Calau", "Brandenburg"));
            licensePlates.put("CAS", new LicensePlate("CAS", "Kreis Recklinghausen", "Castrop-Rauxel", "Nordrhein-Westfalen"));
            licensePlates.put("CB", new LicensePlate("CB", "Stadt Cottbus", "Cottbus", "Brandenburg"));
            licensePlates.put("CE", new LicensePlate("CE", "Landkreis Celle", "Celle", "Niedersachsen"));
            licensePlates.put("CHA", new LicensePlate("CHA", "Landkreis Cham", "Cham", "Bayern"));
            licensePlates.put("CLP", new LicensePlate("CLP", "Landkreis Cloppenburg", "Cloppenburg", "Niedersachsen"));
            licensePlates.put("CLZ", new LicensePlate("CLZ", "Landkreis Goslar", "Clausthal-Zellerfeld", "Niedersachsen"));
            licensePlates.put("CO", new LicensePlate("CO", "Landkreis Coburg (XX 999)", "Coburg", "Bayern"));
            licensePlates.put("COC", new LicensePlate("COC", "Landkreis Cochem-Zell in Cochem", "Cochem", "Rheinland-Pfalz"));
            licensePlates.put("COE", new LicensePlate("COE", "Kreis Coesfeld", "Coesfeld", "Nordrhein-Westfalen"));
            licensePlates.put("CUX", new LicensePlate("CUX", "Landkreis Cuxhaven", "Cuxhaven", "Niedersachsen"));
            licensePlates.put("CW", new LicensePlate("CW", "Landkreis Calw", "Calw", "Baden-Württemberg"));
            licensePlates.put("D", new LicensePlate("D", "Stadt Düsseldorf", "Düsseldorf", "Nordrhein-Westfalen"));
            licensePlates.put("DA", new LicensePlate("DA", "Stadt Darmstadt (XX 999)", "Darmstadt", "Hessen"));
            licensePlates.put("DAH", new LicensePlate("DAH", "Landkreis Dachau", "Dachau", "Bayern"));
            licensePlates.put("DAN", new LicensePlate("DAN", "Landkreis Lüchow-Dannenberg in Lüchow", "Dannenberg", "Niedersachsen"));
            licensePlates.put("DAU", new LicensePlate("DAU", "Landkreis Vulkaneifel in Daun", "Daun", "Rheinland-Pfalz"));
            licensePlates.put("DBR", new LicensePlate("DBR", "Landkreis Rostock", "Bad Doberan", "Mecklenburg-Vorpommern"));
            licensePlates.put("DD", new LicensePlate("DD", "Stadt Dresden", "Dresden", "Sachsen"));
            licensePlates.put("DE", new LicensePlate("DE", "Stadt Dessau-Roßlau", "Dessau", "Sachsen-Anhalt"));
            licensePlates.put("DEG", new LicensePlate("DEG", "Landkreis Deggendorf", "Deggendorf", "Bayern"));
            licensePlates.put("DEL", new LicensePlate("DEL", "Stadt Delmenhorst", "Delmenhorst", "Niedersachsen"));
            licensePlates.put("DGF", new LicensePlate("DGF", "Landkreis Dingolfing-Landau in Dingolfing", "Dingolfing", "Bayern"));
            licensePlates.put("DH", new LicensePlate("DH", "Landkreis Diepholz", "Diepholz", "Niedersachsen"));
            licensePlates.put("DI", new LicensePlate("DI", "Landkreis Darmstadt-Dieburg", "Dieburg", "Hessen"));
            licensePlates.put("DIN", new LicensePlate("DIN", "Kreis Wesel", "Dinslaken", "Nordrhein-Westfalen"));
            licensePlates.put("DL", new LicensePlate("DL", "Landkreis Mittelsachsen", "Döbeln", "Sachsen"));
            licensePlates.put("DLG", new LicensePlate("DLG", "Landkreis Dillingen an der Donau", "Dillingen", "Bayern"));
            licensePlates.put("DM", new LicensePlate("DM", "Altkreis Demmin im Landkreis Mecklenburgische Seenplatte", "Demmin", "Mecklenburg-Vorpommern"));
            licensePlates.put("DN", new LicensePlate("DN", "Kreis Düren", "Düren", "Nordrhein-Westfalen"));
            licensePlates.put("DO", new LicensePlate("DO", "Stadt Dortmund", "Dortmund", "Nordrhein-Westfalen"));
            licensePlates.put("DON", new LicensePlate("DON", "Landkreis Donau-Ries in Donauwörth", "Donauwörth", "Bayern"));
            licensePlates.put("DU", new LicensePlate("DU", "Stadt Duisburg", "Duisburg", "Nordrhein-Westfalen"));
            licensePlates.put("DUD", new LicensePlate("DUD", "Landkreis Göttingen", "Duderstadt", "Niedersachsen"));
            licensePlates.put("DÜW", new LicensePlate("DÜW", "Landkreis Bad Dürkheim", "Bad Dürkheim an der Weinstraße", "Rheinland-Pfalz"));
            licensePlates.put("DW", new LicensePlate("DW", "Landkreis Sächsische Schweiz-Osterzgebirge", "Dippoldiswalde", "Sachsen"));
            licensePlates.put("DZ", new LicensePlate("DZ", "Landkreis Nordsachsen", "Delitzsch", "Sachsen"));
            licensePlates.put("E", new LicensePlate("E", "Stadt Essen", "Essen", "Nordrhein-Westfalen"));
            licensePlates.put("EA", new LicensePlate("EA", "Stadt Eisenach", "Eisenach", "Thüringen"));
            licensePlates.put("EB", new LicensePlate("EB", "Landkreis Nordsachsen", "Eilenburg", "Sachsen"));
            licensePlates.put("EBE", new LicensePlate("EBE", "Landkreis Ebersberg", "Ebersberg", "Bayern"));
            licensePlates.put("ECK", new LicensePlate("ECK", "Kreis Rendsburg-Eckernförde", "Eckernförde", "Schleswig-Holstein"));
            licensePlates.put("ED", new LicensePlate("ED", "Landkreis Erding", "Erding", "Bayern"));
            licensePlates.put("EE", new LicensePlate("EE", "Landkreis Elbe-Elster in Herzberg (Elster)", "Elbe-Elster", "Brandenburg"));
            licensePlates.put("EF", new LicensePlate("EF", "Stadt Erfurt", "Erfurt", "Thüringen"));
            licensePlates.put("EI", new LicensePlate("EI", "Landkreis Eichstätt", "Eichstätt", "Bayern"));
            licensePlates.put("EIC", new LicensePlate("EIC", "Landkreis Eichsfeld in Heilbad Heiligenstadt", "Eichsfeld", "Thüringen"));
            licensePlates.put("EIL", new LicensePlate("EIL", "Landkreis Mansfeld-Südharz", "Eisleben", "Sachsen-Anhalt"));
            licensePlates.put("EIN", new LicensePlate("EIN", "Landkreis Northeim", "Einbeck", "Niedersachsen"));
            licensePlates.put("EIS", new LicensePlate("EIS", "Saale-Holzland-Kreis", "Eisenberg", "Thüringen"));
            licensePlates.put("EL", new LicensePlate("EL", "Landkreis Emsland in Meppen", "Emsland", "Niedersachsen"));
            licensePlates.put("EM", new LicensePlate("EM", "Landkreis Emmendingen", "Emmendingen", "Baden-Württemberg"));
            licensePlates.put("EMD", new LicensePlate("EMD", "Stadt Emden", "Emden", "Niedersachsen"));
            licensePlates.put("EMS", new LicensePlate("EMS", "Rhein-Lahn-Kreis in Bad Ems", "Bad Ems", "Rheinland-Pfalz"));
            licensePlates.put("EN", new LicensePlate("EN", "Ennepe-Ruhr-Kreis in Schwelm", "Ennepe", "Nordrhein-Westfalen"));
            licensePlates.put("ER", new LicensePlate("ER", "Stadt Erlangen", "Erlangen", "Bayern"));
            licensePlates.put("ERB", new LicensePlate("ERB", "Odenwaldkreis in Erbach (Odenwald)", "Erbach", "Hessen"));
            licensePlates.put("ERH", new LicensePlate("ERH", "Landkreis Erlangen-Höchstadt in Erlangen", "Erlangen-Höchstadt", "Bayern"));
            licensePlates.put("ERZ", new LicensePlate("ERZ", "Erzgebirgskreis in Annaberg-Buchholz", "Erzgebirge", "Sachsen"));
            licensePlates.put("ES", new LicensePlate("ES", "Landkreis Esslingen", "Esslingen", "Baden-Württemberg"));
            licensePlates.put("ESW", new LicensePlate("ESW", "Werra-Meißner-Kreis in Eschwege", "Eschwege", "Hessen"));
            licensePlates.put("EU", new LicensePlate("EU", "Kreis Euskirchen", "Euskirchen", "Nordrhein-Westfalen"));
            licensePlates.put("EW", new LicensePlate("EW", "Landkreis Barnim", "Eberswalde", "Brandenburg"));
            licensePlates.put("F", new LicensePlate("F", "Stadt Frankfurt am Main", "Frankfurt", "Hessen"));
            licensePlates.put("FB", new LicensePlate("FB", "Wetteraukreis in Friedberg (Hessen)", "Friedberg", "Hessen"));
            licensePlates.put("FD", new LicensePlate("FD", "Landkreis Fulda", "Fulda", "Hessen"));
            licensePlates.put("FDS", new LicensePlate("FDS", "Landkreis Freudenstadt", "Freudenstadt", "Baden-Württemberg"));
            licensePlates.put("FF", new LicensePlate("FF", "Stadt Frankfurt (Oder)", "Frankfurt", "Brandenburg"));
            licensePlates.put("FFB", new LicensePlate("FFB", "Landkreis Fürstenfeldbruck", "Fürstenfeldbruck", "Bayern"));
            licensePlates.put("FG", new LicensePlate("FG", "Landkreis Mittelsachsen in Freiberg", "Freiberg", "Sachsen"));
            licensePlates.put("FL", new LicensePlate("FL", "Stadt Flensburg", "Flensburg", "Schleswig-Holstein"));
            licensePlates.put("FLÖ", new LicensePlate("FLÖ", "Landkreis Mittelsachsen", "Flöha", "Sachsen"));
            licensePlates.put("FN", new LicensePlate("FN", "Bodenseekreis in Friedrichshafen", "Friedrichshafen", "Baden-Württemberg"));
            licensePlates.put("FO", new LicensePlate("FO", "Landkreis Forchheim", "Forchheim", "Bayern"));
            licensePlates.put("FOR", new LicensePlate("FOR", "Landkreis Spree-Neiße", "Forst (Lausitz)", "Brandenburg"));
            licensePlates.put("FR", new LicensePlate("FR", "Stadt Freiburg im Breisgau (XX 999 und NA-ZZ 9999)", "Freiburg", "Baden-Württemberg"));
            licensePlates.put("FRG", new LicensePlate("FRG", "Landkreis Freyung-Grafenau in Freyung", "Freyung-Grafenau", "Bayern"));
            licensePlates.put("FRI", new LicensePlate("FRI", "Landkreis Friesland in Jever", "Friesland", "Niedersachsen"));
            licensePlates.put("FS", new LicensePlate("FS", "Landkreis Freising", "Freising", "Bayern"));
            licensePlates.put("FT", new LicensePlate("FT", "Stadt Frankenthal (Pfalz)", "Frankenthal", "Rheinland-Pfalz"));
            licensePlates.put("FTL", new LicensePlate("FTL", "Landkreis Sächsische Schweiz-Osterzgebirge", "Freital", "Sachsen"));
            licensePlates.put("FÜ", new LicensePlate("FÜ", "Stadt Fürth (XX 999)", "Fürth", "Bayern"));
            licensePlates.put("G", new LicensePlate("G", "Stadt Gera", "Gera", "Thüringen"));
            licensePlates.put("GA", new LicensePlate("GA", "Altmarkkreis Salzwedel", "Gardelegen", "Sachsen-Anhalt"));
            licensePlates.put("GAN", new LicensePlate("GAN", "Landkreis Northeim", "Bad Gandersheim", "Niedersachsen"));
            licensePlates.put("GAP", new LicensePlate("GAP", "Landkreis Garmisch-Partenkirchen", "Garmisch-Partenkirchen", "Bayern"));
            licensePlates.put("GC", new LicensePlate("GC", "Landkreis Zwickau", "Glauchau", "Sachsen"));
            licensePlates.put("GD", new LicensePlate("GD", "Ostalbkreis", "Schwäbisch Gmünd", "Baden-Württemberg"));
            licensePlates.put("GE", new LicensePlate("GE", "Stadt Gelsenkirchen", "Gelsenkirchen", "Nordrhein-Westfalen"));
            licensePlates.put("GER", new LicensePlate("GER", "Landkreis Germersheim", "Germersheim", "Rheinland-Pfalz"));
            licensePlates.put("GF", new LicensePlate("GF", "Landkreis Gifhorn", "Gifhorn", "Niedersachsen"));
            licensePlates.put("GG", new LicensePlate("GG", "Landkreis Groß-Gerau", "Groß-Gerau", "Hessen"));
            licensePlates.put("GHA", new LicensePlate("GHA", "Landkreis Leipzig", "Geithain", "Sachsen"));
            licensePlates.put("GHC", new LicensePlate("GHC", "Landkreis Wittenberg", "Gräfenhainichen", "Sachsen-Anhalt"));
            licensePlates.put("GI", new LicensePlate("GI", "Landkreis Gießen", "Gießen", "Hessen"));
            licensePlates.put("GL", new LicensePlate("GL", "Rheinisch-Bergischer Kreis in Bergisch Gladbach", "(Bergisch) Gladbach", "Nordrhein-Westfalen"));
            licensePlates.put("GLA", new LicensePlate("GLA", "Kreis Recklinghausen", "Gladbeck", "Nordrhein-Westfalen"));
            licensePlates.put("GM", new LicensePlate("GM", "Oberbergischer Kreis in Gummersbach", "Gummersbach", "Nordrhein-Westfalen"));
            licensePlates.put("GMN", new LicensePlate("GMN", "Landkreis Vorpommern-Rügen", "Grimmen", "Mecklenburg-Vorpommern"));
            licensePlates.put("GN", new LicensePlate("GN", "Main-Kinzig-Kreis (ohne die Stadt Hanau)", "Gelnhausen", "Hessen"));
            licensePlates.put("GNT", new LicensePlate("GNT", "Landkreis Jerichower Land", "Genthin", "Sachsen-Anhalt"));
            licensePlates.put("GÖ", new LicensePlate("GÖ", "Landkreis Göttingen", "Göttingen", "Niedersachsen"));
            licensePlates.put("GOA", new LicensePlate("GOA", "Rhein-Hunsrück-Kreis", "St. Goar", "Rheinland-Pfalz"));
            licensePlates.put("GP", new LicensePlate("GP", "Landkreis Göppingen", "Göppingen", "Baden-Württemberg"));
            licensePlates.put("GR", new LicensePlate("GR", "Landkreis Görlitz", "Görlitz", "Sachsen"));
            licensePlates.put("GRH", new LicensePlate("GRH", "Landkreis Meißen", "Großenhain", "Sachsen"));
            licensePlates.put("GRM", new LicensePlate("GRM", "Landkreis Leipzig", "Grimma", "Sachsen"));
            licensePlates.put("GRZ", new LicensePlate("GRZ", "Landkreis Greiz", "Greiz", "Thüringen"));
            licensePlates.put("GS", new LicensePlate("GS", "Landkreis Goslar", "Goslar", "Niedersachsen"));
            licensePlates.put("GT", new LicensePlate("GT", "Kreis Gütersloh", "Gütersloh", "Nordrhein-Westfalen"));
            licensePlates.put("GTH", new LicensePlate("GTH", "Landkreis Gotha", "Gotha", "Thüringen"));
            licensePlates.put("GÜ", new LicensePlate("GÜ", "Landkreis Rostock", "Güstrow", "Mecklenburg-Vorpommern"));
            licensePlates.put("GUB", new LicensePlate("GUB", "Landkreis Spree-Neiße", "Guben", "Brandenburg"));
            licensePlates.put("GW", new LicensePlate("GW", "Landkreis Vorpommern-Greifswald", "Greifswald", "Mecklenburg-Vorpommern"));
            licensePlates.put("GZ", new LicensePlate("GZ", "Landkreis Günzburg", "Günzburg", "Bayern"));
            licensePlates.put("H", new LicensePlate("H", "Region Hannover", "Hannover", "Niedersachsen"));
            licensePlates.put("HA", new LicensePlate("HA", "Stadt Hagen", "Hagen", "Nordrhein-Westfalen"));
            licensePlates.put("HAL", new LicensePlate("HAL", "Stadt Halle (Saale)", "Halle", "Sachsen-Anhalt"));
            licensePlates.put("HAM", new LicensePlate("HAM", "Stadt Hamm", "Hamm", "Nordrhein-Westfalen"));
            licensePlates.put("HAS", new LicensePlate("HAS", "Landkreis Haßberge in Haßfurt", "Haßberge oder Haßfurt", "Bayern"));
            licensePlates.put("HB", new LicensePlate("HB", "Stadt Bremerhaven (X 9999)", "Hansestadt Bremen", "Bremen"));
            licensePlates.put("HBN", new LicensePlate("HBN", "Landkreis Hildburghausen", "Hildburghausen", "Thüringen"));
            licensePlates.put("HBS", new LicensePlate("HBS", "Landkreis Harz", "Halberstadt", "Sachsen-Anhalt"));
            licensePlates.put("HC", new LicensePlate("HC", "Landkreis Mittelsachsen", "Hainichen", "Sachsen"));
            licensePlates.put("HCH", new LicensePlate("HCH", "Zollernalbkreis", "Hechingen", "Baden-Württemberg"));
            licensePlates.put("HD", new LicensePlate("HD", "Rhein-Neckar-Kreis in Heidelberg (XX 999 und 9999)", "Heidelberg", "Baden-Württemberg"));
            licensePlates.put("HDH", new LicensePlate("HDH", "Landkreis Heidenheim", "Heidenheim", "Baden-Württemberg"));
            licensePlates.put("HDL", new LicensePlate("HDL", "Landkreis Börde", "Haldensleben", "Sachsen-Anhalt"));
            licensePlates.put("HE", new LicensePlate("HE", "Landkreis Helmstedt", "Helmstedt", "Niedersachsen"));
            licensePlates.put("HEF", new LicensePlate("HEF", "Landkreis Hersfeld-Rotenburg in Bad Hersfeld", "Bad Hersfeld", "Hessen"));
            licensePlates.put("HEI", new LicensePlate("HEI", "Kreis Dithmarschen in Heide (Holstein)", "Heide", "Schleswig-Holstein"));
            licensePlates.put("HEL", new LicensePlate("HEL", "Hessen, Landesregierung und Landtag", "Hessischer Landtag", "Hessen"));
            licensePlates.put("HER", new LicensePlate("HER", "Stadt Herne", "Herne", "Nordrhein-Westfalen"));
            licensePlates.put("HET", new LicensePlate("HET", "Landkreis Mansfeld-Südharz", "Hettstedt", "Sachsen-Anhalt"));
            licensePlates.put("HF", new LicensePlate("HF", "Kreis Herford", "Herford", "Nordrhein-Westfalen"));
            licensePlates.put("HG", new LicensePlate("HG", "Hochtaunuskreis in Bad Homburg vor der Höhe", "Bad Homburg", "Hessen"));
            licensePlates.put("HGW", new LicensePlate("HGW", "Stadt Greifswald (Große kreisangehörige Stadt im Landkreis Vorpommern-Greifswald)", "Hansestadt Greifswald", "Mecklenburg-Vorpommern"));
            licensePlates.put("HH", new LicensePlate("HH", "Freie und Hansestadt Hamburg, Senat und Bürgerschaft", "Hansestadt Hamburg", "Hamburg"));
            licensePlates.put("HHM", new LicensePlate("HHM", "Burgenlandkreis", "Hohenmölsen", "Sachsen-Anhalt"));
            licensePlates.put("HI", new LicensePlate("HI", "Landkreis Hildesheim", "Hildesheim", "Niedersachsen"));
            licensePlates.put("HIG", new LicensePlate("HIG", "Landkreis Eichsfeld", "Heiligenstadt", "Thüringen"));
            licensePlates.put("HK", new LicensePlate("HK", "Landkreis Heidekreis in Bad Fallingbostel", "Heidekreis", "Niedersachsen"));
            licensePlates.put("HL", new LicensePlate("HL", "Stadt Lübeck", "Hansestadt Lübeck", "Schleswig-Holstein"));
            licensePlates.put("HM", new LicensePlate("HM", "Landkreis Hameln-Pyrmont in Hameln", "Hameln", "Niedersachsen"));
            licensePlates.put("HMÜ", new LicensePlate("HMÜ", "Landkreis Göttingen", "Hann. Münden", "Niedersachsen"));
            licensePlates.put("HN", new LicensePlate("HN", "Landkreis Heilbronn (XX 999 und AA-MZ 9999)", "Heilbronn", "Baden-Württemberg"));
            licensePlates.put("HO", new LicensePlate("HO", "Landkreis Hof (XX 999)", "Hof", "Bayern"));
            licensePlates.put("HOG", new LicensePlate("HOG", "Landkreis Kassel", "Hofgeismar", "Hessen"));
            licensePlates.put("HOL", new LicensePlate("HOL", "Landkreis Holzminden", "Holzminden", "Niedersachsen"));
            licensePlates.put("HOM", new LicensePlate("HOM", "Saarpfalz-Kreis in Homburg (ohne die Stadt St. Ingbert)", "Homburg", "Saarland"));
            licensePlates.put("HOT", new LicensePlate("HOT", "Landkreis Zwickau", "Hohenstein-Ernstthal", "Sachsen"));
            licensePlates.put("HP", new LicensePlate("HP", "Kreis Bergstraße in Heppenheim (Bergstraße)", "Heppenheim", "Hessen"));
            licensePlates.put("HR", new LicensePlate("HR", "Schwalm-Eder-Kreis in Homberg (Efze)", "Homberg", "Hessen"));
            licensePlates.put("HRO", new LicensePlate("HRO", "Stadt Rostock", "Hansestadt Rostock", "Mecklenburg-Vorpommern"));
            licensePlates.put("HS", new LicensePlate("HS", "Kreis Heinsberg", "Heinsberg", "Nordrhein-Westfalen"));
            licensePlates.put("HSK", new LicensePlate("HSK", "Hochsauerlandkreis in Meschede", "Hochsauerlandkreis", "Nordrhein-Westfalen"));
            licensePlates.put("HST", new LicensePlate("HST", "Stadt Stralsund (Große kreisangehörige Stadt im Landkreis Vorpommern-Rügen)", "Hansestadt Stralsund", "Mecklenburg-Vorpommern"));
            licensePlates.put("HU", new LicensePlate("HU", "Stadt Hanau (Sonderstatusstadt im Main-Kinzig-Kreis)", "Hanau", "Hessen"));
            licensePlates.put("HV", new LicensePlate("HV", "Landkreis Stendal", "Havelberg", "Sachsen-Anhalt"));
            licensePlates.put("HVL", new LicensePlate("HVL", "Landkreis Havelland in Rathenow", "Havelland", "Brandenburg"));
            licensePlates.put("HWI", new LicensePlate("HWI", "Stadt Wismar (Große kreisangehörige Stadt im Landkreis Nordwestmecklenburg)", "Hansestadt Wismar", "Mecklenburg-Vorpommern"));
            licensePlates.put("HX", new LicensePlate("HX", "Kreis Höxter", "Höxter", "Nordrhein-Westfalen"));
            licensePlates.put("HY", new LicensePlate("HY", "Landkreis Bautzen", "Hoyerswerda", "Sachsen"));
            licensePlates.put("HZ", new LicensePlate("HZ", "Landkreis Harz in Halberstadt", "Harz", "Sachsen-Anhalt"));
            licensePlates.put("IGB", new LicensePlate("IGB", "Stadt St. Ingbert (Mittelstadt im Saarpfalz-Kreis)", "St. Ingbert", "Saarland"));
            licensePlates.put("IK", new LicensePlate("IK", "Ilm-Kreis in Arnstadt", "Ilm-Kreis", "Thüringen"));
            licensePlates.put("IL", new LicensePlate("IL", "Ilm-Kreis", "Ilmenau", "Thüringen"));
            licensePlates.put("IN", new LicensePlate("IN", "Stadt Ingolstadt", "Ingolstadt", "Bayern"));
            licensePlates.put("IZ", new LicensePlate("IZ", "Kreis Steinburg in Itzehoe", "Itzehoe", "Schleswig-Holstein"));
            licensePlates.put("J", new LicensePlate("J", "Stadt Jena", "Jena", "Thüringen"));
            licensePlates.put("JE", new LicensePlate("JE", "Landkreis Wittenberg", "Jessen (Elster)", "Sachsen-Anhalt"));
            licensePlates.put("JL", new LicensePlate("JL", "Landkreis Jerichower Land in Burg", "Jerichower Land", "Sachsen-Anhalt"));
            licensePlates.put("JÜL", new LicensePlate("JÜL", "Kreis Düren", "Jülich", "Nordrhein-Westfalen"));
            licensePlates.put("K", new LicensePlate("K", "Stadt Köln", "Köln", "Nordrhein-Westfalen"));
            licensePlates.put("KA", new LicensePlate("KA", "Stadt Karlsruhe (XX 999 und NA-ZZ 9999)", "Karlsruhe", "Baden-Württemberg"));
            licensePlates.put("KB", new LicensePlate("KB", "Landkreis Waldeck-Frankenberg in Korbach", "Korbach", "Hessen"));
            licensePlates.put("KC", new LicensePlate("KC", "Landkreis Kronach", "Kronach", "Bayern"));
            licensePlates.put("KE", new LicensePlate("KE", "Stadt Kempten (Allgäu)", "Kempten", "Bayern"));
            licensePlates.put("KEH", new LicensePlate("KEH", "Landkreis Kelheim", "Kelheim", "Bayern"));
            licensePlates.put("KF", new LicensePlate("KF", "Stadt Kaufbeuren", "Kaufbeuren", "Bayern"));
            licensePlates.put("KG", new LicensePlate("KG", "Landkreis Bad Kissingen", "Bad Kissingen", "Bayern"));
            licensePlates.put("KH", new LicensePlate("KH", "Landkreis Bad Kreuznach", "Bad Kreuznach", "Rheinland-Pfalz"));
            licensePlates.put("KI", new LicensePlate("KI", "Stadt Kiel", "Kiel", "Schleswig-Holstein"));
            licensePlates.put("KIB", new LicensePlate("KIB", "Donnersbergkreis in Kirchheimbolanden", "Kirchheimbolanden", "Rheinland-Pfalz"));
            licensePlates.put("KL", new LicensePlate("KL", "Landkreis Kaiserslautern (XX 999)", "Kaiserslautern", "Rheinland-Pfalz"));
            licensePlates.put("KLE", new LicensePlate("KLE", "Kreis Kleve", "Kleve", "Nordrhein-Westfalen"));
            licensePlates.put("KLZ", new LicensePlate("KLZ", "Altmarkkreis Salzwedel", "Klötze", "Sachsen-Anhalt"));
            licensePlates.put("KM", new LicensePlate("KM", "Landkreis Bautzen", "Kamenz", "Sachsen"));
            licensePlates.put("KN", new LicensePlate("KN", "Landkreis Konstanz (ohne die Gemeinde Büsingen am Hochrhein)", "Konstanz", "Baden-Württemberg"));
            licensePlates.put("KO", new LicensePlate("KO", "Stadt Koblenz", "Koblenz", "Rheinland-Pfalz"));
            licensePlates.put("KÖT", new LicensePlate("KÖT", "Landkreis Anhalt-Bitterfeld", "Köthen (Anhalt)", "Sachsen-Anhalt"));
            licensePlates.put("KR", new LicensePlate("KR", "Stadt Krefeld", "Krefeld", "Nordrhein-Westfalen"));
            licensePlates.put("KS", new LicensePlate("KS", "Stadt Kassel (XX 999)", "Kassel", "Hessen"));
            licensePlates.put("KT", new LicensePlate("KT", "Landkreis Kitzingen", "Kitzingen", "Bayern"));
            licensePlates.put("KU", new LicensePlate("KU", "Landkreis Kulmbach", "Kulmbach", "Bayern"));
            licensePlates.put("KÜN", new LicensePlate("KÜN", "Hohenlohekreis in Künzelsau", "Künzelsau", "Baden-Württemberg"));
            licensePlates.put("KUS", new LicensePlate("KUS", "Landkreis Kusel", "Kusel", "Rheinland-Pfalz"));
            licensePlates.put("KY", new LicensePlate("KY", "Landkreis Ostprignitz-Ruppin", "Kyritz", "Brandenburg"));
            licensePlates.put("KYF", new LicensePlate("KYF", "Kyffhäuserkreis in Sondershausen", "Kyffhäuser", "Thüringen"));
            licensePlates.put("L", new LicensePlate("L", "Stadt Leipzig (A?T und AA-TZ)", "Leipzig", "Sachsen"));
            licensePlates.put("LA", new LicensePlate("LA", "Landkreis Landshut (XX 999)", "Landshut", "Bayern"));
            licensePlates.put("LAU", new LicensePlate("LAU", "Landkreis Nürnberger Land in Lauf an der Pegnitz", "Lauf", "Bayern"));
            licensePlates.put("LB", new LicensePlate("LB", "Landkreis Ludwigsburg", "Ludwigsburg", "Baden-Württemberg"));
            licensePlates.put("LBS", new LicensePlate("LBS", "Saale-Orla-Kreis", "Lobenstein", "Thüringen"));
            licensePlates.put("LD", new LicensePlate("LD", "Stadt Landau in der Pfalz", "Landau", "Rheinland-Pfalz"));
            licensePlates.put("LDK", new LicensePlate("LDK", "Lahn-Dill-Kreis in Wetzlar (ohne die Stadt Wetzlar)", "Lahn-Dill-Kreis", "Hessen"));
            licensePlates.put("LDS", new LicensePlate("LDS", "Landkreis Dahme-Spreewald in Lübben (Spreewald)", "Landkreis Dahme-Spreewald", "Brandenburg"));
            licensePlates.put("LEO", new LicensePlate("LEO", "Landkreis Böblingen", "Leonberg", "Baden-Württemberg"));
            licensePlates.put("LER", new LicensePlate("LER", "Landkreis Leer", "Leer", "Niedersachsen"));
            licensePlates.put("LEV", new LicensePlate("LEV", "Stadt Leverkusen", "Leverkusen", "Nordrhein-Westfalen"));
            licensePlates.put("LG", new LicensePlate("LG", "Landkreis Lüneburg", "Lüneburg", "Niedersachsen"));
            licensePlates.put("LI", new LicensePlate("LI", "Landkreis Lindau (Bodensee)", "Lindau", "Bayern"));
            licensePlates.put("LIF", new LicensePlate("LIF", "Landkreis Lichtenfels", "Lichtenfels", "Bayern"));
            licensePlates.put("LIP", new LicensePlate("LIP", "Kreis Lippe in Detmold", "Lippe", "Nordrhein-Westfalen"));
            licensePlates.put("LL", new LicensePlate("LL", "Landkreis Landsberg am Lech", "Landsberg am Lech", "Bayern"));
            licensePlates.put("LM", new LicensePlate("LM", "Landkreis Limburg-Weilburg in Limburg an der Lahn", "Limburg", "Hessen"));
            licensePlates.put("LÖ", new LicensePlate("LÖ", "Landkreis Lörrach", "Lörrach", "Baden-Württemberg"));
            licensePlates.put("LÖB", new LicensePlate("LÖB", "Landkreis Görlitz", "Löbau", "Sachsen"));
            licensePlates.put("LOS", new LicensePlate("LOS", "Landkreis Oder-Spree in Beeskow", "Landkreis Oder-Spree", "Brandenburg"));
            licensePlates.put("LP", new LicensePlate("LP", "Kreis Soest", "Lippstadt", "Nordrhein-Westfalen"));
            licensePlates.put("LRO", new LicensePlate("LRO", "Landkreis Rostock in Güstrow", "Landkreis Rostock", "Mecklenburg-Vorpommern"));
            licensePlates.put("LSA", new LicensePlate("LSA", "Sachsen-Anhalt, Landesregierung, Landtag und Polizei[2]", "Land Sachsen-Anhalt", "Sachsen-Anhalt"));
            licensePlates.put("LSN", new LicensePlate("LSN", "Sachsen, Landesregierung und Landtag", "Landtag Sachsen", "Sachsen"));
            licensePlates.put("LSZ", new LicensePlate("LSZ", "Unstrut-Hainich-Kreis", "Bad Langensalza", "Thüringen"));
            licensePlates.put("LU", new LicensePlate("LU", "Stadt Ludwigshafen am Rhein", "Ludwigshafen", "Rheinland-Pfalz"));
            licensePlates.put("LÜN", new LicensePlate("LÜN", "Kreis Unna", "Lünen", "Nordrhein-Westfalen"));
            licensePlates.put("LWL", new LicensePlate("LWL", "Landkreis Ludwigslust (jetzt Landkreis Ludwigslust-Parchim)", "Ludwigslust", "Mecklenburg-Vorpommern"));
            licensePlates.put("M", new LicensePlate("M", "Stadt München (XX 999 und 9999)", "München", "Bayern"));
            licensePlates.put("MA", new LicensePlate("MA", "Stadt Mannheim", "Mannheim", "Baden-Württemberg"));
            licensePlates.put("MAB", new LicensePlate("MAB", "Erzgebirgskreis", "Marienberg", "Sachsen"));
            licensePlates.put("MB", new LicensePlate("MB", "Landkreis Miesbach", "Miesbach", "Bayern"));
            licensePlates.put("MD", new LicensePlate("MD", "Stadt Magdeburg", "Magdeburg", "Sachsen-Anhalt"));
            licensePlates.put("ME", new LicensePlate("ME", "Kreis Mettmann", "Mettmann", "Nordrhein-Westfalen"));
            licensePlates.put("MEI", new LicensePlate("MEI", "Landkreis Meißen", "Meißen", "Sachsen"));
            licensePlates.put("MEK", new LicensePlate("MEK", "Erzgebirgskreis", "Mittlerer Erzgebirgskreis", "Sachsen"));
            licensePlates.put("MER", new LicensePlate("MER", "Saalekreis", "Merseburg", "Sachsen-Anhalt"));
            licensePlates.put("MG", new LicensePlate("MG", "Stadt Mönchengladbach", "Mönchengladbach", "Nordrhein-Westfalen"));
            licensePlates.put("MGN", new LicensePlate("MGN", "Landkreis Schmalkalden-Meiningen", "Meiningen", "Thüringen"));
            licensePlates.put("MH", new LicensePlate("MH", "Stadt Mülheim an der Ruhr", "Mülheim an der Ruhr", "Nordrhein-Westfalen"));
            licensePlates.put("MHL", new LicensePlate("MHL", "Unstrut-Hainich-Kreis", "Mühlhausen/Thüringen", "Thüringen"));
            licensePlates.put("MI", new LicensePlate("MI", "Kreis Minden-Lübbecke in Minden", "Minden", "Nordrhein-Westfalen"));
            licensePlates.put("MIL", new LicensePlate("MIL", "Landkreis Miltenberg", "Miltenberg", "Bayern"));
            licensePlates.put("MK", new LicensePlate("MK", "Märkischer Kreis in Lüdenscheid", "Grafschaft Mark", "Nordrhein-Westfalen"));
            licensePlates.put("MKK", new LicensePlate("MKK", "Main-Kinzig-Kreis in Gelnhausen (ohne die Stadt Hanau)", "Main-Kinzig-Kreis", "Hessen"));
            licensePlates.put("ML", new LicensePlate("ML", "Landkreis Mansfeld-Südharz", "Mansfelder Land", "Sachsen-Anhalt"));
            licensePlates.put("MM", new LicensePlate("MM", "Stadt Memmingen", "Memmingen", "Bayern"));
            licensePlates.put("MN", new LicensePlate("MN", "Landkreis Unterallgäu in Mindelheim", "Mindelheim", "Bayern"));
            licensePlates.put("MO", new LicensePlate("MO", "Kreis Wesel", "Moers", "Nordrhein-Westfalen"));
            licensePlates.put("MOL", new LicensePlate("MOL", "Landkreis Märkisch-Oderland in Seelow", "Märkisch-Oderland", "Brandenburg"));
            licensePlates.put("MOS", new LicensePlate("MOS", "Neckar-Odenwald-Kreis in Mosbach", "Mosbach", "Baden-Württemberg"));
            licensePlates.put("MQ", new LicensePlate("MQ", "Saalekreis", "Merseburg-Querfurt", "Sachsen-Anhalt"));
            licensePlates.put("MR", new LicensePlate("MR", "Landkreis Marburg-Biedenkopf in Marburg", "Marburg-Biedenkopf", "Hessen"));
            licensePlates.put("MS", new LicensePlate("MS", "Stadt Münster (Westfalen)", "Münster", "Nordrhein-Westfalen"));
            licensePlates.put("MSH", new LicensePlate("MSH", "Landkreis Mansfeld-Südharz in Sangerhausen", "Mansfeld-Südharz", "Sachsen-Anhalt"));
            licensePlates.put("MSP", new LicensePlate("MSP", "Landkreis Main-Spessart in Karlstadt", "Main-Spessart", "Bayern"));
            licensePlates.put("MST", new LicensePlate("MST", "Landkreis Mecklenburg-Strelitz in Neustrelitz (jetzt Landkreis Mecklenburgische Seenplatte)", "Mecklenburg-Strelitz", "Mecklenburg-Vorpommern"));
            licensePlates.put("MTK", new LicensePlate("MTK", "Main-Taunus-Kreis in Hofheim am Taunus", "Main-Taunus-Kreis", "Hessen"));
            licensePlates.put("MTL", new LicensePlate("MTL", "Landkreis Leipzig", "Muldentalkreis", "Sachsen"));
            licensePlates.put("MÜ", new LicensePlate("MÜ", "Landkreis Mühldorf am Inn", "Mühldorf", "Bayern"));
            licensePlates.put("MÜR", new LicensePlate("MÜR", "ehemaliger Landkreis Müritz im Landkreis Mecklenburgische Seenplatte", "Müritz", "Mecklenburg-Vorpommern"));
            licensePlates.put("MVL", new LicensePlate("MVL", "Mecklenburg-Vorpommern, Landesregierung, Landtag und Polizei[2]", "Mecklenburg-Vorpommerscher Landtag", "Mecklenburg-Vorpommern"));
            licensePlates.put("MW", new LicensePlate("MW", "Landkreis Mittelsachsen", "Mittweida", "Sachsen"));
            licensePlates.put("MYK", new LicensePlate("MYK", "Landkreis Mayen-Koblenz in Koblenz", "Mayen-Koblenz", "Rheinland-Pfalz"));
            licensePlates.put("MZ", new LicensePlate("MZ", "Stadt Mainz (XX 999 und AA?KY 9999)", "Mainz", "Rheinland-Pfalz"));
            licensePlates.put("MZG", new LicensePlate("MZG", "Landkreis Merzig-Wadern in Merzig", "Merzig", "Saarland"));
            licensePlates.put("N", new LicensePlate("N", "Stadt Nürnberg", "Nürnberg", "Bayern"));
            licensePlates.put("NB", new LicensePlate("NB", "Stadt Neubrandenburg (Große kreisangehörige Stadt im Landkreis Mecklenburgische Seenplatte)", "Neubrandenburg", "Mecklenburg-Vorpommern"));
            licensePlates.put("ND", new LicensePlate("ND", "Landkreis Neuburg-Schrobenhausen in Neuburg an der Donau", "Neuburg an der Donau", "Bayern"));
            licensePlates.put("NDH", new LicensePlate("NDH", "Landkreis Nordhausen", "Nordhausen", "Thüringen"));
            licensePlates.put("NE", new LicensePlate("NE", "Rhein-Kreis Neuss in Neuss", "Neuss", "Nordrhein-Westfalen"));
            licensePlates.put("NEA", new LicensePlate("NEA", "Landkreis Neustadt an der Aisch-Bad Windsheim in Neustadt an der Aisch", "Neustadt an der Aisch", "Bayern"));
            licensePlates.put("NEB", new LicensePlate("NEB", "Burgenlandkreis", "Nebra", "Sachsen-Anhalt"));
            licensePlates.put("NES", new LicensePlate("NES", "Landkreis Rhön-Grabfeld in Bad Neustadt an der Saale", "Bad Neustadt an der Saale", "Bayern"));
            licensePlates.put("NEW", new LicensePlate("NEW", "Landkreis Neustadt an der Waldnaab", "Neustadt an der Waldnaab", "Bayern"));
            licensePlates.put("NF", new LicensePlate("NF", "Kreis Nordfriesland in Husum", "Nordfriesland", "Schleswig-Holstein"));
            licensePlates.put("NH", new LicensePlate("NH", "Landkreis Sonneberg", "Neuhaus am Rennweg", "Thüringen"));
            licensePlates.put("NI", new LicensePlate("NI", "Landkreis Nienburg/Weser", "Nienburg/Weser", "Niedersachsen"));
            licensePlates.put("NK", new LicensePlate("NK", "Landkreis Neunkirchen in Ottweiler", "Neunkirchen", "Saarland"));
            licensePlates.put("NL", new LicensePlate("NL", "Niedersachsen, Landesregierung und Landtag", "Niedersächsischer Landtag", "Niedersachsen"));
            licensePlates.put("NM", new LicensePlate("NM", "Landkreis Neumarkt in der Oberpfalz", "Neumarkt", "Bayern"));
            licensePlates.put("NMB", new LicensePlate("NMB", "Burgenlandkreis", "Naumburg", "Sachsen-Anhalt"));
            licensePlates.put("NMS", new LicensePlate("NMS", "Stadt Neumünster", "Neumünster", "Schleswig-Holstein"));
            licensePlates.put("NOH", new LicensePlate("NOH", "Landkreis Grafschaft Bentheim in Nordhorn", "Nordhorn", "Niedersachsen"));
            licensePlates.put("NOL", new LicensePlate("NOL", "Landkreis Görlitz", "Niederschlesischer Oberlausitzkreis", "Sachsen"));
            licensePlates.put("NOM", new LicensePlate("NOM", "Landkreis Northeim", "Northeim", "Niedersachsen"));
            licensePlates.put("NOR", new LicensePlate("NOR", "Landkreis Aurich", "Norden", "Niedersachsen"));
            licensePlates.put("NP", new LicensePlate("NP", "Landkreis Ostprignitz-Ruppin", "Neuruppin", "Brandenburg"));
            licensePlates.put("NR", new LicensePlate("NR", "Landkreis Neuwied", "Neuwied am Rhein", "Rheinland-Pfalz"));
            licensePlates.put("NRW", new LicensePlate("NRW", "Nordrhein-Westfalen, Landesregierung, Landtag und Polizei[2]", "Nordrhein-Westfalen", "Nordrhein-Westfalen"));
            licensePlates.put("NU", new LicensePlate("NU", "Landkreis Neu-Ulm", "Neu-Ulm", "Bayern"));
            licensePlates.put("NVP", new LicensePlate("NVP", "Landkreis Vorpommern-Rügen", "Nordvorpommern", "Mecklenburg-Vorpommern"));
            licensePlates.put("NW", new LicensePlate("NW", "Stadt Neustadt an der Weinstraße", "Neustadt an der Weinstraße", "Rheinland-Pfalz"));
            licensePlates.put("NWM", new LicensePlate("NWM", "Landkreis Nordwestmecklenburg in Wismar (ohne Stadt Wismar)", "Nordwestmecklenburg", "Mecklenburg-Vorpommern"));
            licensePlates.put("NY", new LicensePlate("NY", "Landkreis Görlitz", "Niesky", "Sachsen"));
            licensePlates.put("OA", new LicensePlate("OA", "Landkreis Oberallgäu in Sonthofen", "Oberallgäu", "Bayern"));
            licensePlates.put("OAL", new LicensePlate("OAL", "Landkreis Ostallgäu in Marktoberdorf", "Ostallgäu", "Bayern"));
            licensePlates.put("OB", new LicensePlate("OB", "Stadt Oberhausen", "Oberhausen", "Nordrhein-Westfalen"));
            licensePlates.put("OBG", new LicensePlate("OBG", "Landkreis Stendal", "Osterburg", "Sachsen-Anhalt"));
            licensePlates.put("OC", new LicensePlate("OC", "Landkreis Börde", "Oschersleben", "Sachsen-Anhalt"));
            licensePlates.put("OD", new LicensePlate("OD", "Kreis Stormarn in Bad Oldesloe", "Bad Oldesloe", "Schleswig-Holstein"));
            licensePlates.put("OE", new LicensePlate("OE", "Kreis Olpe", "Olpe", "Nordrhein-Westfalen"));
            licensePlates.put("OF", new LicensePlate("OF", "Landkreis Offenbach in Dietzenbach (XX 999 und 9999)", "Offenbach", "Hessen"));
            licensePlates.put("OG", new LicensePlate("OG", "Ortenaukreis in Offenburg", "Offenburg", "Baden-Württemberg"));
            licensePlates.put("OH", new LicensePlate("OH", "Kreis Ostholstein in Eutin", "Ostholstein", "Schleswig-Holstein"));
            licensePlates.put("OHA", new LicensePlate("OHA", "Landkreis Osterode am Harz", "Osterode am Harz", "Niedersachsen"));
            licensePlates.put("OHV", new LicensePlate("OHV", "Landkreis Oberhavel in Oranienburg", "Oberhavel", "Brandenburg"));
            licensePlates.put("OHZ", new LicensePlate("OHZ", "Landkreis Osterholz in Osterholz-Scharmbeck", "Osterholz", "Niedersachsen"));
            licensePlates.put("OK", new LicensePlate("OK", "Landkreis Börde", "Ohrekreis", "Sachsen-Anhalt"));
            licensePlates.put("OL", new LicensePlate("OL", "Stadt Oldenburg (Oldenburg) (XX 999)", "Oldenburg", "Niedersachsen"));
            licensePlates.put("OPR", new LicensePlate("OPR", "Landkreis Ostprignitz-Ruppin in Neuruppin", "Ostprignitz-Ruppin", "Brandenburg"));
            licensePlates.put("OS", new LicensePlate("OS", "Landkreis Osnabrück (XX 999)", "Osnabrück", "Niedersachsen"));
            licensePlates.put("OSL", new LicensePlate("OSL", "Landkreis Oberspreewald-Lausitz in Senftenberg", "Oberspreewald-Lausitz", "Brandenburg"));
            licensePlates.put("OVL", new LicensePlate("OVL", "Vogtlandkreis", "Obervogtland", "Sachsen"));
            licensePlates.put("OVP", new LicensePlate("OVP", "Landkreis Vorpommern-Greifswald", "Ostvorpommern", "Mecklenburg-Vorpommern"));
            licensePlates.put("OZ", new LicensePlate("OZ", "Landkreis Nordsachsen", "Oschatz", "Sachsen"));
            licensePlates.put("P", new LicensePlate("P", "Stadt Potsdam", "Potsdam", "Brandenburg"));
            licensePlates.put("PA", new LicensePlate("PA", "Landkreis Passau (XX 9, 99 und 999)", "Passau", "Bayern"));
            licensePlates.put("PAF", new LicensePlate("PAF", "Landkreis Pfaffenhofen an der Ilm", "Pfaffenhofen", "Bayern"));
            licensePlates.put("PAN", new LicensePlate("PAN", "Landkreis Rottal-Inn in Pfarrkirchen", "Pfarrkirchen", "Bayern"));
            licensePlates.put("PB", new LicensePlate("PB", "Kreis Paderborn", "Paderborn", "Nordrhein-Westfalen"));
            licensePlates.put("PCH", new LicensePlate("PCH", "Landkreis Parchim (jetzt Landkreis Ludwigslust-Parchim)", "Parchim", "Mecklenburg-Vorpommern"));
            licensePlates.put("PE", new LicensePlate("PE", "Landkreis Peine", "Peine", "Niedersachsen"));
            licensePlates.put("PF", new LicensePlate("PF", "Stadt Pforzheim (XX 999 und NA-ZZ 9999)", "Pforzheim", "Baden-Württemberg"));
            licensePlates.put("PI", new LicensePlate("PI", "Kreis Pinneberg", "Pinneberg", "Schleswig-Holstein"));
            licensePlates.put("PIR", new LicensePlate("PIR", "Landkreis Sächsische Schweiz-Osterzgebirge in Pirna", "Pirna", "Sachsen"));
            licensePlates.put("PL", new LicensePlate("PL", "Vogtlandkreis", "Plauen", "Sachsen"));
            licensePlates.put("PLÖ", new LicensePlate("PLÖ", "Kreis Plön", "Plön", "Schleswig-Holstein"));
            licensePlates.put("PM", new LicensePlate("PM", "Landkreis Potsdam-Mittelmark in Bad Belzig", "Potsdam-Mittelmark", "Brandenburg"));
            licensePlates.put("PN", new LicensePlate("PN", "Saale-Orla-Kreis", "Pößneck", "Thüringen"));
            licensePlates.put("PR", new LicensePlate("PR", "Landkreis Prignitz in Perleberg", "Prignitz", "Brandenburg"));
            licensePlates.put("PRÜ", new LicensePlate("PRÜ", "Eifelkreis Bitburg-Prüm", "Prüm", "Rheinland-Pfalz"));
            licensePlates.put("PS", new LicensePlate("PS", "Landkreis Südwestpfalz in Pirmasens (XX 99 und 999)", "Pirmasens", "Rheinland-Pfalz"));
            licensePlates.put("PW", new LicensePlate("PW", "Landkreis Vorpommern-Greifswald", "Pasewalk", "Mecklenburg-Vorpommern"));
            licensePlates.put("QFT", new LicensePlate("QFT", "Saalekreis", "Querfurt", "Sachsen-Anhalt"));
            licensePlates.put("QLB", new LicensePlate("QLB", "Landkreis Harz", "Quedlinburg", "Sachsen-Anhalt"));
            licensePlates.put("R", new LicensePlate("R", "Stadt Regensburg (XX 999 und 9999)", "Regensburg", "Bayern"));
            licensePlates.put("RA", new LicensePlate("RA", "Landkreis Rastatt", "Rastatt", "Baden-Württemberg"));
            licensePlates.put("RC", new LicensePlate("RC", "Vogtlandkreis", "Reichenbach im Vogtland", "Sachsen"));
            licensePlates.put("RD", new LicensePlate("RD", "Kreis Rendsburg-Eckernförde in Rendsburg", "Rendsburg", "Schleswig-Holstein"));
            licensePlates.put("RDG", new LicensePlate("RDG", "Landkreis Vorpommern-Rügen", "Ribnitz-Damgarten", "Mecklenburg-Vorpommern"));
            licensePlates.put("RE", new LicensePlate("RE", "Kreis Recklinghausen", "Recklinghausen", "Nordrhein-Westfalen"));
            licensePlates.put("REG", new LicensePlate("REG", "Landkreis Regen", "Regen", "Bayern"));
            licensePlates.put("RG", new LicensePlate("RG", "Landkreis Meißen", "Landkreis Riesa-Großenhain", "Sachsen"));
            licensePlates.put("RH", new LicensePlate("RH", "Landkreis Roth", "Roth", "Bayern"));
            licensePlates.put("RI", new LicensePlate("RI", "Landkreis Schaumburg", "Rinteln", "Niedersachsen"));
            licensePlates.put("RIE", new LicensePlate("RIE", "Landkreis Meißen", "Riesa", "Sachsen"));
            licensePlates.put("RL", new LicensePlate("RL", "Landkreis Mittelsachsen", "Rochlitz", "Sachsen"));
            licensePlates.put("RO", new LicensePlate("RO", "Landkreis Rosenheim ", "Rosenheim", "Bayern"));
            licensePlates.put("ROS", new LicensePlate("ROS", "Landkreis Rostock", "Rostock", "Mecklenburg-Vorpommern"));
            licensePlates.put("ROW", new LicensePlate("ROW", "Landkreis Rotenburg (Wümme)", "Rotenburg an der Wümme", "Niedersachsen"));
            licensePlates.put("RP", new LicensePlate("RP", "Rhein-Pfalz-Kreis in Ludwigshafen am Rhein", "Rhein-Pfalz", "Rheinland-Pfalz"));
            licensePlates.put("RPL", new LicensePlate("RPL", "Rheinland-Pfalz, Landesregierung, Landtag und Polizei[2]", "Rheinland-Pfälzischer Landtag", "Rheinland-Pfalz"));
            licensePlates.put("RS", new LicensePlate("RS", "Stadt Remscheid", "Remscheid", "Nordrhein-Westfalen"));
            licensePlates.put("RSL", new LicensePlate("RSL", "Stadt Dessau-Roßlau", "Roßlau (Elbe)", "Sachsen-Anhalt"));
            licensePlates.put("RT", new LicensePlate("RT", "Landkreis Reutlingen", "Reutlingen", "Baden-Württemberg"));
            licensePlates.put("RU", new LicensePlate("RU", "Landkreis Saalfeld-Rudolstadt", "Rudolstadt", "Thüringen"));
            licensePlates.put("RÜD", new LicensePlate("RÜD", "Rheingau-Taunus-Kreis in Bad Schwalbach", "Rüdesheim", "Hessen"));
            licensePlates.put("RÜG", new LicensePlate("RÜG", "Landkreis Vorpommern-Rügen", "Rügen", "Mecklenburg-Vorpommern"));
            licensePlates.put("RV", new LicensePlate("RV", "Landkreis Ravensburg", "Ravensburg", "Baden-Württemberg"));
            licensePlates.put("RW", new LicensePlate("RW", "Landkreis Rottweil", "Rottweil", "Baden-Württemberg"));
            licensePlates.put("RZ", new LicensePlate("RZ", "Kreis Herzogtum Lauenburg in Ratzeburg", "Ratzeburg", "Schleswig-Holstein"));
            licensePlates.put("S", new LicensePlate("S", "Stadt Stuttgart", "Stuttgart", "Baden-Württemberg"));
            licensePlates.put("SAB", new LicensePlate("SAB", "Landkreis Trier-Saarburg", "Saarburg", "Rheinland-Pfalz"));
            licensePlates.put("SAD", new LicensePlate("SAD", "Landkreis Schwandorf", "Schwandorf", "Bayern"));
            licensePlates.put("SAL", new LicensePlate("SAL", "Saarland, Landesregierung, Landtag und Polizei[2]", "Saarländischer Landtag", "Saarland"));
            licensePlates.put("SAW", new LicensePlate("SAW", "Altmarkkreis Salzwedel in Salzwedel", "Salzwedel", "Sachsen-Anhalt"));
            licensePlates.put("SB", new LicensePlate("SB", "Regionalverband Saarbrücken (ohne die Stadt Völklingen)", "Saarbrücken", "Saarland"));
            licensePlates.put("SBK", new LicensePlate("SBK", "Salzlandkreis", "Schönebeck (Elbe)", "Sachsen-Anhalt"));
            licensePlates.put("SC", new LicensePlate("SC", "Stadt Schwabach", "Schwabach", "Bayern"));
            licensePlates.put("SCZ", new LicensePlate("SCZ", "Saale-Orla-Kreis", "Schleiz", "Thüringen"));
            licensePlates.put("SDH", new LicensePlate("SDH", "Kyffhäuserkreis", "Sondershausen", "Thüringen"));
            licensePlates.put("SDL", new LicensePlate("SDL", "Landkreis Stendal", "Stendal", "Sachsen-Anhalt"));
            licensePlates.put("SE", new LicensePlate("SE", "Kreis Segeberg in Bad Segeberg", "Bad Segeberg", "Schleswig-Holstein"));
            licensePlates.put("SEB", new LicensePlate("SEB", "Landkreis Sächsische Schweiz-Osterzgebirge", "Sebnitz", "Sachsen"));
            licensePlates.put("SFB", new LicensePlate("SFB", "Landkreis Oberspreewald-Lausitz", "Senftenberg", "Brandenburg"));
            licensePlates.put("SFT", new LicensePlate("SFT", "Salzlandkreis", "Staßfurt", "Sachsen-Anhalt"));
            licensePlates.put("SG", new LicensePlate("SG", "Stadt Solingen", "Solingen", "Nordrhein-Westfalen"));
            licensePlates.put("SGH", new LicensePlate("SGH", "Landkreis Mansfeld-Südharz", "Sangerhausen", "Sachsen-Anhalt"));
            licensePlates.put("SH", new LicensePlate("SH", "Schleswig-Holstein, Landesregierung, Landtag und Polizei[2]", "Schleswig-Holstein", "Schleswig-Holstein"));
            licensePlates.put("SHA", new LicensePlate("SHA", "Landkreis Schwäbisch Hall", "Schwäbisch Hall", "Baden-Württemberg"));
            licensePlates.put("SHG", new LicensePlate("SHG", "Landkreis Schaumburg in Stadthagen", "Schaumburg", "Niedersachsen"));
            licensePlates.put("SHK", new LicensePlate("SHK", "Saale-Holzland-Kreis in Eisenberg (Thüringen)", "Saale-Holzland-Kreis", "Thüringen"));
            licensePlates.put("SHL", new LicensePlate("SHL", "Stadt Suhl", "Suhl", "Thüringen"));
            licensePlates.put("SI", new LicensePlate("SI", "Kreis Siegen-Wittgenstein in Siegen", "Siegen", "Nordrhein-Westfalen"));
            licensePlates.put("SIG", new LicensePlate("SIG", "Landkreis Sigmaringen", "Sigmaringen", "Baden-Württemberg"));
            licensePlates.put("SIM", new LicensePlate("SIM", "Rhein-Hunsrück-Kreis in Simmern/Hunsrück", "Simmern", "Rheinland-Pfalz"));
            licensePlates.put("SK", new LicensePlate("SK", "Saalekreis in Merseburg", "Saalekreis", "Sachsen-Anhalt"));
            licensePlates.put("SL", new LicensePlate("SL", "Kreis Schleswig-Flensburg in Schleswig", "Schleswig", "Schleswig-Holstein"));
            licensePlates.put("SLE", new LicensePlate("SLE", "Kreis Euskirchen", "Schleiden", "Nordrhein-Westfalen"));
            licensePlates.put("SLF", new LicensePlate("SLF", "Landkreis Saalfeld-Rudolstadt in Saalfeld/Saale", "Saalfeld", "Thüringen"));
            licensePlates.put("SLK", new LicensePlate("SLK", "Salzlandkreis in Bernburg", "Salzlandkreis", "Sachsen-Anhalt"));
            licensePlates.put("SLN", new LicensePlate("SLN", "Landkreis Altenburger Land", "Schmölln", "Thüringen"));
            licensePlates.put("SLS", new LicensePlate("SLS", "Landkreis Saarlouis", "Saarlouis", "Saarland"));
            licensePlates.put("SLÜ", new LicensePlate("SLÜ", "Main-Kinzig-Kreis (ohne die Stadt Hanau)", "Schlüchtern", "Hessen"));
            licensePlates.put("SLZ", new LicensePlate("SLZ", "Wartburgkreis", "Bad Salzungen", "Thüringen"));
            licensePlates.put("SM", new LicensePlate("SM", "Landkreis Schmalkalden-Meiningen in Meiningen", "Schmalkalden-Meiningen", "Thüringen"));
            licensePlates.put("SN", new LicensePlate("SN", "Stadt Schwerin", "Schwerin", "Mecklenburg-Vorpommern"));
            licensePlates.put("SO", new LicensePlate("SO", "Kreis Soest", "Soest", "Nordrhein-Westfalen"));
            licensePlates.put("SOK", new LicensePlate("SOK", "Saale-Orla-Kreis in Schleiz", "Saale-Orla-Kreis", "Thüringen"));
            licensePlates.put("SÖM", new LicensePlate("SÖM", "Landkreis Sömmerda", "Sömmerda", "Thüringen"));
            licensePlates.put("SON", new LicensePlate("SON", "Landkreis Sonneberg", "Sonneberg", "Thüringen"));
            licensePlates.put("SP", new LicensePlate("SP", "Stadt Speyer", "Speyer", "Rheinland-Pfalz"));
            licensePlates.put("SPB", new LicensePlate("SPB", "Landkreis Spree-Neiße", "Spremberg", "Brandenburg"));
            licensePlates.put("SPN", new LicensePlate("SPN", "Landkreis Spree-Neiße in Forst (Lausitz)", "Spree-Neiße", "Brandenburg"));
            licensePlates.put("SR", new LicensePlate("SR", "Landkreis Straubing-Bogen in Straubing (XX 99 und 999)", "Straubing", "Bayern"));
            licensePlates.put("SRO", new LicensePlate("SRO", "Saale-Holzland-Kreis", "Stadtroda", "Thüringen"));
            licensePlates.put("ST", new LicensePlate("ST", "Kreis Steinfurt", "Steinfurt", "Nordrhein-Westfalen"));
            licensePlates.put("STA", new LicensePlate("STA", "Landkreis Starnberg", "Starnberg", "Bayern"));
            licensePlates.put("STD", new LicensePlate("STD", "Landkreis Stade", "Stade", "Niedersachsen"));
            licensePlates.put("STL", new LicensePlate("STL", "Erzgebirgskreis", "Stollberg/Erzgeb.", "Sachsen"));
            licensePlates.put("SU", new LicensePlate("SU", "Rhein-Sieg-Kreis in Siegburg", "Siegburg", "Nordrhein-Westfalen"));
            licensePlates.put("SÜW", new LicensePlate("SÜW", "Landkreis Südliche Weinstraße in Landau in der Pfalz", "Südliche Weinstraße", "Rheinland-Pfalz"));
            licensePlates.put("SW", new LicensePlate("SW", "Landkreis Schweinfurt (XX 999 und XX 9999)", "Schweinfurt", "Bayern"));
            licensePlates.put("SZ", new LicensePlate("SZ", "Stadt Salzgitter", "Salzgitter", "Niedersachsen"));
            licensePlates.put("SZB", new LicensePlate("SZB", "Erzgebirgskreis", "Schwarzenberg/Erzgeb.", "Sachsen"));
            licensePlates.put("TBB", new LicensePlate("TBB", "Main-Tauber-Kreis in Tauberbischofsheim", "Tauberbischofsheim", "Baden-Württemberg"));
            licensePlates.put("TDO", new LicensePlate("TDO", "Landkreis Nordsachsen in Torgau", "Torgau, Delitzsch, Oschatz", "Sachsen"));
            licensePlates.put("TET", new LicensePlate("TET", "Landkreis Rostock", "Teterow", "Mecklenburg-Vorpommern"));
            licensePlates.put("TF", new LicensePlate("TF", "Landkreis Teltow-Fläming in Luckenwalde", "Teltow-Fläming", "Brandenburg"));
            licensePlates.put("TG", new LicensePlate("TG", "Landkreis Nordsachsen", "Torgau", "Sachsen"));
            licensePlates.put("THL", new LicensePlate("THL", "Thüringen, Landesregierung und Landtag", "Thüringer Landtag", "Thüringen"));
            licensePlates.put("THW", new LicensePlate("THW", "Bundesanstalt Technisches Hilfswerk", "Technisches Hilfswerk", "bundesweit"));
            licensePlates.put("TIR", new LicensePlate("TIR", "Landkreis Tirschenreuth", "Tirschenreuth", "Bayern"));
            licensePlates.put("TO", new LicensePlate("TO", "Landkreis Nordsachsen", "Landkreis Torgau-Oschatz", "Sachsen"));
            licensePlates.put("TÖL", new LicensePlate("TÖL", "Landkreis Bad Tölz-Wolfratshausen in Bad Tölz", "Bad Tölz", "Bayern"));
            licensePlates.put("TR", new LicensePlate("TR", "Landkreis Trier-Saarburg in Trier", "Trier", "Rheinland-Pfalz"));
            licensePlates.put("TS", new LicensePlate("TS", "Landkreis Traunstein", "Traunstein", "Bayern"));
            licensePlates.put("TÜ", new LicensePlate("TÜ", "Landkreis Tübingen", "Tübingen", "Baden-Württemberg"));
            licensePlates.put("TUT", new LicensePlate("TUT", "Landkreis Tuttlingen", "Tuttlingen", "Baden-Württemberg"));
            licensePlates.put("UE", new LicensePlate("UE", "Landkreis Uelzen", "Uelzen", "Niedersachsen"));
            licensePlates.put("UEM", new LicensePlate("UEM", "Landkreis Vorpommern-Greifswald", "Ueckermünde", "Mecklenburg-Vorpommern"));
            licensePlates.put("UER", new LicensePlate("UER", "Landkreis Vorpommern-Greifswald", "Uecker-Randow", "Mecklenburg-Vorpommern"));
            licensePlates.put("UH", new LicensePlate("UH", "Unstrut-Hainich-Kreis in Mühlhausen/Thüringen", "Unstrut-Hainich", "Thüringen"));
            licensePlates.put("UL", new LicensePlate("UL", "Alb-Donau-Kreis in Ulm (XX 999 und NA-ZZ 9999)", "Ulm", "Baden-Württemberg"));
            licensePlates.put("UM", new LicensePlate("UM", "Landkreis Uckermark in Prenzlau", "Uckermark", "Brandenburg"));
            licensePlates.put("UN", new LicensePlate("UN", "Kreis Unna", "Unna", "Nordrhein-Westfalen"));
            licensePlates.put("USI", new LicensePlate("USI", "Hochtaunuskreis", "Usingen", "Hessen"));
            licensePlates.put("V", new LicensePlate("V", "Vogtlandkreis in Plauen", "Vogtland", "Sachsen"));
            licensePlates.put("VB", new LicensePlate("VB", "Vogelsbergkreis in Lauterbach (Hessen)", "Vogelsberg", "Hessen"));
            licensePlates.put("VEC", new LicensePlate("VEC", "Landkreis Vechta", "Vechta", "Niedersachsen"));
            licensePlates.put("VER", new LicensePlate("VER", "Landkreis Verden", "Verden", "Niedersachsen"));
            licensePlates.put("VG", new LicensePlate("VG", "Landkreis Vorpommern-Greifswald", "Vorpommern, Greifswald", "Mecklenburg-Vorpommern"));
            licensePlates.put("VIE", new LicensePlate("VIE", "Kreis Viersen", "Viersen", "Nordrhein-Westfalen"));
            licensePlates.put("VK", new LicensePlate("VK", "Stadt Völklingen (Mittelstadt im Regionalverband Saarbrücken)", "Völklingen", "Saarland"));
            licensePlates.put("VR", new LicensePlate("VR", "Landkreis Vorpommern-Rügen", "Vorpommern, Rügen", "Mecklenburg-Vorpommern"));
            licensePlates.put("VS", new LicensePlate("VS", "Schwarzwald-Baar-Kreis", "Villingen-Schwenningen", "Baden-Württemberg"));
            licensePlates.put("W", new LicensePlate("W", "Stadt Wuppertal", "Wuppertal", "Nordrhein-Westfalen"));
            licensePlates.put("WAF", new LicensePlate("WAF", "Kreis Warendorf", "Warendorf", "Nordrhein-Westfalen"));
            licensePlates.put("WAK", new LicensePlate("WAK", "Wartburgkreis in Bad Salzungen", "Wartburgkreis", "Thüringen"));
            licensePlates.put("WAN", new LicensePlate("WAN", "Stadt Herne", "Wanne-Eickel", "Nordrhein-Westfalen"));
            licensePlates.put("WAT", new LicensePlate("WAT", "Stadt Bochum", "Wattenscheid", "Nordrhein-Westfalen"));
            licensePlates.put("WB", new LicensePlate("WB", "Landkreis Wittenberg", "Wittenberg", "Sachsen-Anhalt"));
            licensePlates.put("WBS", new LicensePlate("WBS", "Landkreis Eichsfeld", "Worbis", "Thüringen"));
            licensePlates.put("WDA", new LicensePlate("WDA", "Landkreis Zwickau", "Werdau", "Sachsen"));
            licensePlates.put("WE", new LicensePlate("WE", "Stadt Weimar", "Weimar", "Thüringen"));
            licensePlates.put("WEL", new LicensePlate("WEL", "Landkreis Limburg-Weilburg", "Weilburg", "Hessen"));
            licensePlates.put("WEN", new LicensePlate("WEN", "Stadt Weiden in der Oberpfalz", "Weiden", "Bayern"));
            licensePlates.put("WES", new LicensePlate("WES", "Kreis Wesel", "Wesel", "Nordrhein-Westfalen"));
            licensePlates.put("WF", new LicensePlate("WF", "Landkreis Wolfenbüttel", "Wolfenbüttel", "Niedersachsen"));
            licensePlates.put("WHV", new LicensePlate("WHV", "Stadt Wilhelmshaven", "Wilhelmshaven", "Niedersachsen"));
            licensePlates.put("WI", new LicensePlate("WI", "Stadt Wiesbaden", "Wiesbaden", "Hessen"));
            licensePlates.put("WIL", new LicensePlate("WIL", "Landkreis Bernkastel-Wittlich in Wittlich", "Wittlich", "Rheinland-Pfalz"));
            licensePlates.put("WIT", new LicensePlate("WIT", "Ennepe-Ruhr-Kreis", "Witten", "Nordrhein-Westfalen"));
            licensePlates.put("WK", new LicensePlate("WK", "Landkreis Ostprignitz-Ruppin", "Wittstock/Dosse", "Brandenburg"));
            licensePlates.put("WL", new LicensePlate("WL", "Landkreis Harburg in Winsen (Luhe)", "Winsen (Luhe)", "Niedersachsen"));
            licensePlates.put("WLG", new LicensePlate("WLG", "Landkreis Vorpommern-Greifswald", "Wolgast", "Mecklenburg-Vorpommern"));
            licensePlates.put("WM", new LicensePlate("WM", "Landkreis Weilheim-Schongau in Weilheim in Oberbayern", "Weilheim", "Bayern"));
            licensePlates.put("WMS", new LicensePlate("WMS", "Landkreis Börde", "Wolmirstedt", "Sachsen-Anhalt"));
            licensePlates.put("WN", new LicensePlate("WN", "Rems-Murr-Kreis in Waiblingen", "Waiblingen", "Baden-Württemberg"));
            licensePlates.put("WND", new LicensePlate("WND", "Landkreis St. Wendel", "St. Wendel", "Saarland"));
            licensePlates.put("WO", new LicensePlate("WO", "Stadt Worms", "Worms", "Rheinland-Pfalz"));
            licensePlates.put("WOB", new LicensePlate("WOB", "Stadt Wolfsburg", "Wolfsburg", "Niedersachsen"));
            licensePlates.put("WOH", new LicensePlate("WOH", "Landkreis Kassel", "Wolfhagen", "Hessen"));
            licensePlates.put("WR", new LicensePlate("WR", "Landkreis Harz", "Wernigerode", "Sachsen-Anhalt"));
            licensePlates.put("WSF", new LicensePlate("WSF", "Burgenlandkreis", "Weißenfels", "Sachsen-Anhalt"));
            licensePlates.put("WST", new LicensePlate("WST", "Landkreis Ammerland in Westerstede", "Westerstede", "Niedersachsen"));
            licensePlates.put("WSW", new LicensePlate("WSW", "Landkreis Görlitz", "Weißwasser", "Sachsen"));
            licensePlates.put("WT", new LicensePlate("WT", "Landkreis Waldshut in Waldshut-Tiengen", "Waldshut-Tiengen", "Baden-Württemberg"));
            licensePlates.put("WTM", new LicensePlate("WTM", "Landkreis Wittmund", "Wittmund", "Niedersachsen"));
            licensePlates.put("WÜ", new LicensePlate("WÜ", "Stadt Würzburg", "Würzburg", "Bayern"));
            licensePlates.put("WUG", new LicensePlate("WUG", "Landkreis Weißenburg-Gunzenhausen in Weißenburg in Bayern", "Weißenburg", "Bayern"));
            licensePlates.put("WUN", new LicensePlate("WUN", "Landkreis Wunsiedel im Fichtelgebirge", "Wunsiedel", "Bayern"));
            licensePlates.put("WUR", new LicensePlate("WUR", "Landkreis Leipzig", "Wurzen", "Sachsen"));
            licensePlates.put("WW", new LicensePlate("WW", "Westerwaldkreis in Montabaur", "Westerwald", "Rheinland-Pfalz"));
            licensePlates.put("WZ", new LicensePlate("WZ", "Stadt Wetzlar (Sonderstatusstadt im Lahn-Dill-Kreis)", "Wetzlar", "Hessen"));
            licensePlates.put("WZL", new LicensePlate("WZL", "Landkreis Börde", "Wanzleben", "Sachsen-Anhalt"));
            licensePlates.put("X", new LicensePlate("X", "Internationale Hauptquartiere (NATO)", "NATO", "bundesweit"));
            licensePlates.put("Y", new LicensePlate("Y", "Bundeswehr", "Bundeswehr", "bundesweit"));
            licensePlates.put("Z", new LicensePlate("Z", "Landkreis Zwickau", "Zwickau", "Sachsen"));
            licensePlates.put("ZE", new LicensePlate("ZE", "Landkreis Anhalt-Bitterfeld", "Zerbst/Anhalt", "Sachsen-Anhalt"));
            licensePlates.put("ZEL", new LicensePlate("ZEL", "Landkreis Cochem-Zell", "Zell (Mosel)", "Rheinland-Pfalz"));
            licensePlates.put("ZI", new LicensePlate("ZI", "Landkreis Görlitz", "Zittau", "Sachsen"));
            licensePlates.put("ZP", new LicensePlate("ZP", "Erzgebirgskreis", "Zschopau", "Sachsen"));
            licensePlates.put("ZR", new LicensePlate("ZR", "Landkreis Greiz", "Zeulenroda", "Thüringen"));
            licensePlates.put("ZW", new LicensePlate("ZW", "Stadt Zweibrücken", "Zweibrücken", "Rheinland-Pfalz"));
            licensePlates.put("ZZ", new LicensePlate("ZZ", "Burgenlandkreis", "Zeitz", "Sachsen-Anhalt"));
    }

    public LicensePlate getLicensePlate(String tag)
    {
        if(licensePlates != null && licensePlates.containsKey(tag)){
            return (LicensePlate)licensePlates.get(tag);
        }
        else {
            return null;
        }
    }

}
